spring.application.name=PingMe



# DataSource Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/ReMindrDatabase
spring.datasource.username=postgres
spring.datasource.password=Adarsh@1127
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


# jwt secret key
jwt.secret=TmV3U2VjcmV0S2V5Rm9ySldUU2lnbmluZ1B1cnBvc2VzMTIzNDU2Nzg=

#ollama model selection
spring.ai.ollama.chat.options.model=deepseek-r1:8b

# gemini api key
adarsh.api.key=AIzaSyB5zHauWTxsoB-RubBzvtnuV2WD6Am-IgU

# Spring email properties
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=Edura.learningapp@gmail.com
spring.mail.password=qlgl mmxw nuim mcxa
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true